[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
level = "error"

# String format for logging messages. If logger.datetimeFormat is set,
# logger messages will default to `%(asctime)s.%(msecs)03d %(message)s`. See
# Python's documentation for available attributes:
# https://docs.python.org/2.6/develop/logging.html#formatter-objects
# Default: "%(asctime)s %(message)s"
messageFormat = "%(asctime)s %(message)s"

[client]
showSidebarNavigation = false
# toolbarMode="minimal"

[theme]
base="dark"
backgroundColor="#0b0b0e"

[server]
enableStaticServing = true

[runner]
magicEnabled = true
enforceSerializableSessionState = true